name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build1
      run: go get github.com/edsrzf/mmap-go; go build -v mmap.go
    - name: Build2   
      run: go build -v inc.go

    - name: Test1
      run: go test -v mmap.go
    - name: Test2
      run: go test -v inc.go
